[script://bin/kline_spider.py]
enable = true
cron=hour=15,minute=10

[script://bin/rule_engine.py]
enable = true
cron=hour=09,minute=00

[script://bin/news_spider.py]
enable = true
interval = 30s

[script://bin/covert_qlib.py]
enable = true
cron=hour=18,minute=0

[script://bin/news_analysis.py]
enable = true
cron=hour=23,minute=50