[script://bin/kline_spider.py]
enable = false
cron=hour=16,minute=10

[script://bin/rule_engine.py]
enable = false
cron=hour=18,minute=00

[script://bin/test.py]
enable = true
cron=hour=21,minute=26

[script://bin/news_spider.py]
enable = false
interval = 30s