[script://bin/kline_spider.py]
enable = true
cron=hour=18,minute=10

[script://bin/rule_engine.py]
enable = true
cron=hour=08,minute=00

[script://bin/news_spider.py]
enable = false
interval = 30s

[script://bin/covert_qlib.py]
enable = true
cron=hour=18,minute=0